name = "CodeProofTheArena"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["CodeProofTheArena"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[require]]
name = "SafeVerify"
git = "https://github.com/GasStationManager/SafeVerify.git"


[[lean_lib]]
name = "CodeProofTheArena"
