"""Add owner_id to challenges

Revision ID: 1fe89fc6a18f
Revises: bb314d1e428a
Create Date: 2024-09-28 07:16:50.405221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fe89fc6a18f'
down_revision: Union[str, None] = 'bb314d1e428a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenges', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'challenges', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'challenges', type_='foreignkey')
    op.drop_column('challenges', 'owner_id')
    # ### end Alembic commands ###
