"""update submissions

Revision ID: 2d62d4517dce
Revises: 5bd0e0a04e0c
Create Date: 2024-09-28 22:36:18.462748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d62d4517dce'
down_revision: Union[str, None] = '5bd0e0a04e0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('feedback', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'feedback')
    # ### end Alembic commands ###
