"""Add theorem2_signature to challenges

Revision ID: 3284fb1b9b67
Revises: 4b777e24b130
Create Date: 2024-11-13 22:38:20.214381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3284fb1b9b67'
down_revision: Union[str, None] = '4b777e24b130'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenges', sa.Column('theorem2_signature', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('challenges', 'theorem2_signature')
    # ### end Alembic commands ###
