"""Add proof2 and related fields to submissions

Revision ID: 5169b67d6dcc
Revises: 3284fb1b9b67
Create Date: 2024-11-13 23:09:42.476701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5169b67d6dcc'
down_revision: Union[str, None] = '3284fb1b9b67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('proof2', sa.Text(), nullable=True))
    op.add_column('submissions', sa.Column('is_correct2', sa.Boolean(), nullable=True))
    op.add_column('submissions', sa.Column('feedback2', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'feedback2')
    op.drop_column('submissions', 'is_correct2')
    op.drop_column('submissions', 'proof2')
    # ### end Alembic commands ###
